### PR TITLE
Nightly benchmark setup

### PR DESCRIPTION
**Pull request by quasiben**
This PR adds the infrastructure to run nightly benchmark against latest in dask and distributed.  Once a day, the benchmark will run and create the following:

- performance reports
- plots
- raw timings

All of these will be uploaded and an issue will be created with something like following:

```
Dask Version: 2.30.0
Distributed Version: 2.30.1
simple
	 1.010e+00 +/- 2.356e-02
shuffle
	 5.248e+01 +/- 3.753e+00
rand_access
	 1.204e-02 +/- 3.074e-03

## Plots
<link to plot>

## Performance Reports

simple report
shuffle report
rand-access report

## Raw Values
simple
	 [1.03984618 0.98223996 1.00799799]
shuffle
	 [48.57776427 57.54775286 51.31839633]
rand_access
	 [0.01253104 0.00805187 0.01553202]
```

While 2.30.1/2.30.0 runs smoothly, on the latest of dask/distributed I will occasionally see runs error out with messages like:

```
distributed.utils_perf - WARNING - full garbage collections took 10% CPU time recently (threshold: 10%)
distributed.worker - ERROR - "('split-shuffle-1-fede3a8707071e731c27f45ab446c5b7', 1, (16, 2))"
Traceback (most recent call last):
  File "/Users/bzaitlen/Documents/GitHub/distributed/distributed/worker.py", line 2001, in gather_dep
    deps_ts = [self.tasks[key] for key in deps]
  File "/Users/bzaitlen/Documents/GitHub/distributed/distributed/worker.py", line 2001, in <listcomp>
    deps_ts = [self.tasks[key] for key in deps]
KeyError: "('split-shuffle-1-fede3a8707071e731c27f45ab446c5b7', 1, (16, 2))"
```

I'm running on my laptop which I think should be fine...but I will probably be running these on another machine long term

cc @mrocklin should you have thoughts on output styling and/or the errors.

### CODE REVIEW

**Comment by mrocklin** [comment]
cc @gforsyth on the error message in case he has a moment

**Comment by quasiben** [comment]
I think @gforsyth already resolved this issue with https://github.com/dask/distributed/pull/4241

**Comment by mrocklin** [comment]
Ah, great

**Comment by quasiben** [comment]
This PR now produces issues like https://github.com/quasiben/dask-scheduler-performance/issues/24 .  @jakirkham any issue with merging this in ?  Also, I think we can close #5

**Comment by jakirkham** [comment]
Not from me. Sure sounds good. Thanks Ben!

**Pull request merged**
